version: "3.9"

networks:
  cs_net:

volumes:
  cs_tmp:
  caddy_data:
  caddy_config:

services:
  api:
    container_name: cs-api
    build:
      context: ..
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    env_file:
      - ./stack.env
    volumes:
      - cs_tmp:/data/tmp
      # If using Google Cloud STT, mount credentials and set env var:
      # - ./gcp-credentials.json:/secrets/gcp-credentials.json:ro
    environment:
      # Uncomment if using mounted credentials
      # - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-credentials.json
      - TMP_DIR=/data/tmp
    networks:
      - cs_net

  caddy:
    image: caddy:2
    container_name: cs-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    networks:
      - cs_net


