version: "3.9"

networks:
  cs_net:

volumes:
  cs_tmp:
  caddy_data:
  caddy_config:

services:
  api:
    image: docker.io/egoisticfoil/crucialspace-api:latest
    container_name: cs-api
    restart: unless-stopped
    env_file:
      - ./stack.env
    environment:
      - TMP_DIR=/data/tmp
    volumes:
      - cs_tmp:/data/tmp
      # If using Google Cloud STT, mount credentials and set env var:
      # - ./gcp-credentials.json:/secrets/gcp-credentials.json:ro
      # - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-credentials.json
    networks:
      - cs_net
    ports:
      - "8000:8000"

  # Optional: Enable to get automatic HTTPS via Caddy (set your domain below)
  caddy:
    image: caddy:2
    container_name: cs-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    networks:
      - cs_net


