networks:
  cs_net:

volumes:
  cs_tmp:

services:
  api:
    image: docker.io/egoisticfoil/crucialspace-api:latest
    container_name: cs-api
    restart: unless-stopped
    env_file:
      - ./stack.env
    environment:
      - TMP_DIR=/data/tmp
    volumes:
      - cs_tmp:/data/tmp
      # If using Google Cloud STT, mount credentials and set env var:
      # - ./gcp-credentials.json:/secrets/gcp-credentials.json:ro
      # - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-credentials.json
    networks:
      - cs_net
    ports:
      - "8000:8000"


